version: '2'
services:
  app:
    container_name: app
    build: .
    environment:
      - TEST_ENV=test
    ports:
      - 5000:5000
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - db-data:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db-data:
